<template>
    <div class="destinationContent-box">
        <destination-left :data="all" @cityIndex="cityIndex"></destination-left>
        <destination-right :data="all[i]"></destination-right>
    </div>
</template>

<script>
    import destinationLeft from "./destinationLeft";
    import destinationRight from "./destinationRight";
    export default {
        name: "destinationContent",
        components:{
            destinationLeft,
            destinationRight
        },
        methods:{
            cityIndex(i){
                this.i=i
            }
        },
        data(){
            return {
                i:0,
                all:[
                    {
                        province:"陕西",
                        pid:"1",
                        city:[
                            {
                                cid:"1",
                                cityImg:"./images/destinationRight/destinationRight-zx(1).jpg",
                                cityName:"西安"
                            },
                            {
                                cid:"2",
                                cityImg:"./images/destinationRight/destinationRight-zx(2).jpg",
                                cityName:"咸阳"
                            },
                            {
                                cid:"3",
                                cityImg:"./images/destinationRight/destinationRight-zx(3).jpg",
                                cityName:"宝鸡"
                            },
                            {
                                cid:"4",
                                cityImg:"./images/destinationRight/destinationRight-zx(4).jpg",
                                cityName:"汉中"
                            },
                            {
                                cid:"5",
                                cityImg:"./images/destinationRight/destinationRight-zx(5).jpg",
                                cityName:"延安"
                            },
                        ]
                    },
                    {
                        province:"海南",
                        pid:"2",
                        city:[
                            {
                                cid:"1",
                                cityImg:"./images/destinationRight/destinationRight-zx(6).jpg",
                                cityName:"三亚"
                            },
                            {
                                cid:"2",
                                cityImg:"./images/destinationRight/destinationRight-zx(7).jpg",
                                cityName:"海口"
                            },
                            {
                                cid:"3",
                                cityImg:"./images/destinationRight/destinationRight-zx(8).jpg",
                                cityName:"兴隆"
                            }
                        ]
                    },
                    {
                        province:"云南",
                        pid:"3",
                        city:[
                            {
                                cid:"1",
                                cityImg:"./images/destinationRight/destinationRight-zx(9).jpg",
                                cityName:"丽江"
                            },
                            {
                                cid:"2",
                                cityImg:"./images/destinationRight/destinationRight-zx(10).jpg",
                                cityName:"大理"
                            },
                            {
                                cid:"3",
                                cityImg:"./images/destinationRight/destinationRight-zx(11).jpg",
                                cityName:"西双版纳"
                            },
                            {
                                cid:"4",
                                cityImg:"./images/destinationRight/destinationRight-zx(12).jpg",
                                cityName:"香格里拉"
                            }
                        ]
                    },
                    {
                        province:"四川",
                        pid:"4",
                        city:[
                            {
                                cid:"1",
                                cityImg:"./images/destinationRight/destinationRight-zx(13).jpg",
                                cityName:"成都"
                            },
                            {
                                cid:"2",
                                cityImg:"./images/destinationRight/destinationRight-zx(14).jpg",
                                cityName:"都江堰"
                            },
                            {
                                cid:"3",
                                cityImg:"./images/destinationRight/destinationRight-zx(15).jpg",
                                cityName:"九寨沟"
                            },
                            {
                                cid:"4",
                                cityImg:"./images/destinationRight/destinationRight-zx(16).jpg",
                                cityName:"稻城"
                            }
                        ]
                    },
                    {
                        province:"福建",
                        pid:"5",
                        city:[
                            {
                                cid:"1",
                                cityImg:"./images/destinationRight/destinationRight-zx(17).jpg",
                                cityName:"厦门"
                            },
                            {
                                cid:"2",
                                cityImg:"./images/destinationRight/destinationRight-zx(18).jpg",
                                cityName:"鼓浪屿"
                            }
                        ]
                    },
                    {
                        province:"广东",
                        pid:"6",
                        city:[
                            {
                                cid:"1",
                                cityImg:"./images/destinationRight/destinationRight-zx(19).jpg",
                                cityName:"广州"
                            },
                            {
                                cid:"2",
                                cityImg:"./images/destinationRight/destinationRight-zx(20).jpg",
                                cityName:"珠海"
                            }
                        ]
                    },
                    {
                        province:"广西",
                        pid:"7",
                        city:[
                            {
                                cid:"1",
                                cityImg:"./images/destinationRight/destinationRight-zx(21).jpg",
                                cityName:"桂林"
                            },
                            {
                                cid:"2",
                                cityImg:"./images/destinationRight/destinationRight-zx(22).jpg",
                                cityName:"南宁"
                            }
                        ]
                    },
                    {
                        province:"黑龙江",
                        pid:"8",
                        city:[
                            {
                                cid:"1",
                                cityImg:"./images/destinationRight/destinationRight-zx(23).jpg",
                                cityName:"哈尔滨"
                            },
                            {
                                cid:"2",
                                cityImg:"./images/destinationRight/destinationRight-zx(24).jpg",
                                cityName:"大连"
                            }
                        ]
                    },
                    {
                        province:"湖北",
                        pid:"9",
                        city:[
                            {
                                cid:"1",
                                cityImg:"./images/destinationRight/destinationRight-zx(25).jpg",
                                cityName:"武汉"
                            },
                            {
                                cid:"2",
                                cityImg:"./images/destinationRight/destinationRight-zx(26).jpg",
                                cityName:"荆门"
                            },
                            {
                                cid:"3",
                                cityImg:"./images/destinationRight/destinationRight-zx(27).jpg",
                                cityName:"黄冈"
                            }
                        ]
                    },
                    {
                        province:"湖南",
                        pid:"10",
                        city:[
                            {
                                cid:"1",
                                cityImg:"./images/destinationRight/destinationRight-zx(28).jpg",
                                cityName:"长沙"
                            },
                            {
                                cid:"2",
                                cityImg:"./images/destinationRight/destinationRight-zx(29).jpg",
                                cityName:"张家界"
                            }
                        ]
                    },
                    {
                        province:"江西",
                        pid:"11",
                        city:[
                            {
                                cid:"1",
                                cityImg:"./images/destinationRight/destinationRight-zx(30).jpg",
                                cityName:"南昌"
                            },
                            {
                                cid:"2",
                                cityImg:"./images/destinationRight/destinationRight-zx(31).jpg",
                                cityName:"宜春"
                            }
                        ]
                    },
                ]
            }
        }
    }
</script>

<style scoped>
.destinationContent-box{
    width: 100%;
    display: flex;
    justify-content: space-between;
    margin-top: 1.1rem;
    margin-bottom: 0.5rem;
}
</style>